CREATE TABLE IF NOT EXISTS subjects (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS students (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    birth_date TEXT NOT NULL,
    mark REAL NOT NULL DEFAULT 5.0,
    subject_id INTEGER,
    status TEXT DEFAULT 'pay',

    FOREIGN KEY (subject_id) REFERENCES subjects (id)
);